FEATURE_VECTOR_SIZE = 159
TARGET_FRAMES = 45

PREDICTION_INTERVAL = 0.05

IDLE_SIGN_NAME = "idle"
CONFIDENCE_THRESHOLD = 0.90
PREDICTION_HISTORY_FRAMES = 20
MIN_PREDICTION_STABILITY = 0.8

CAMERA_INDEX = 1
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720